version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cleanarch
    ports:
      - 3306:3306
    volumes:
      - "./migration/create_table_orders.sql:/docker-entrypoint-initdb.d/create_table_orders.sql"
