// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	ID    int     `json:"id"`
	Price float64 `json:"Price"`
	Tax   float64 `json:"Tax"`
}

type FindAllOrdersByPageInput struct {
	Page  *int    `json:"Page,omitempty"`
	Limit *int    `json:"Limit,omitempty"`
	Sort  *string `json:"Sort,omitempty"`
}

type FindAllOrdersByPageOutput struct {
	Paging *Paging  `json:"Paging,omitempty"`
	Orders []*Order `json:"Orders"`
}

type Order struct {
	ID         int     `json:"id"`
	Price      float64 `json:"Price"`
	Tax        float64 `json:"Tax"`
	FinalPrice float64 `json:"FinalPrice"`
	CreatedAt  string  `json:"CreatedAt"`
}

type Paging struct {
	Limit  int `json:"Limit"`
	Offset int `json:"Offset"`
	Total  int `json:"Total"`
}
